### ISSUE TITLE
How to use as a client?

### ISSUE THREAD

**Issue by therealprof** [ntex-rs/ntex-mqtt#11]
I'd like to use actix-mqtt as a MQTT client but I'm struggling a bit getting it to work for anything more than a one-shot message QoS0 PUBLISH message after a CONNECT as exercised by tests/test_server.rs. The problem boils down to the connection automatically being dropped after calling the `state` function, also the `ClientSession` which is passed to the `ack.state` is simply dropped and the rest of the callbacks like `finish` never even called.

What is the right way to keep the session open and how can the session be used to actually interface with actors?

**Comment by fafhrd91** [comment]
0.5-0.8 implements simple api
