### ISSUE TITLE
how to use mpsc::channel to dispatch msg when handle incoming publishes and how to subscribe to multiple topics in one API call?

### ISSUE THREAD

**Issue by xudesheng** [ntex-rs/ntex-mqtt#111]
Kindly help me for two questions:
1) How to subscribe to multiple topics (all with the same`SubscriptionOptions`) in one call?
2) I want to dispatch the incoming publishes through a mpsc::Sender to different thread to process the msg without blocking the client. However, I can't find a proper way to let `fn_service(|control: v5::client::ControlMessage<Error>|` use a mpsc::Sender I created. using the client router `client.resource("response", publish)` has the same challenge.

Appreciate.

**Comment by fafhrd91** [comment]
1. you just call topic_filter multiple time, sink.subscribe().topic_filter(“topic1”).topic_filter(“topic2”) etc
2. post compilation error, you may need to do something like fn_service(move |…

btw this is for discussions rather than issues

**Comment by xudesheng** [comment]
> 1. you just call topic_filter multiple time, sink.subscribe().topic_filter(“topic1”).topic_filter(“topic2”) etc
> 2. post compilation error, you may need to do something like fn_service(move |…
> 
> btw this is for discussions rather than issues

Thank you!!! yes, the `fn_service(move | ` works. One more question:

The `publish.ack(Success)` consumes the entire `publish` but indeed it only needs the `packet_id`. I have to copy `topic` and `payload` when I want to send the content out.

Is there an API like: `pub fn ack(&self, reason_code: codec::PublishAckReason) -> ControlResult` which doesn't need the entire `publish` to create a control message? The current API is: `pub fn ack(self, reason_code: codec::PublishAckReason) -> ControlResult`.



```
v5::client::ControlMessage::Publish(publish) => {
                log::info!(
                    "incoming publish: {:?} -> {:?} payload {:?}",
                    publish.packet().packet_id,
                    publish.packet().topic,
                    publish.packet().payload
                );
                let res = publish.ack(v5::codec::PublishAckReason::Success); // the publish is consumed here.
                if let Err(e) = tx.send(publish) { //can't send it anymore.
                    log::error!("Error sending publish: {:?}", e);
                }

                Ready::Ok(res)
            }
```

**Comment by xudesheng** [comment]
close and move to discussion.
