### ISSUE TITLE
connect to "broker-cn.emqx.io:8883"/"54.87.92.106:8883" fail by openssl 

### ISSUE THREAD

**Issue by jm-observer** [ntex-rs/ntex-mqtt#119]
hello, when i connect to these addr like "broker-cn.emqx.io:8883" or "54.87.92.106:8883" by openssl. The original program will parse hostname to "broker-cn.emqx.io:8883" or "54.87.92.106:8883", but the dns name in cert is "broker-cn.emqx.io", so it will connect fail.

please see these [examples](https://github.com/jm-observer/ntex-example) that same addr, but the result is different. the reason is [Parsing hostname error](https://github.com/ntex-rs/ntex/blob/master/ntex-connect/src/message.rs#L31)

**Comment by jm-observer** [comment]
You can refer to a [pull request](https://github.com/ntex-rs/ntex/pull/150) I made that is closed

**Comment by fafhrd91** [comment]
fixed in ntex-connect
