### ISSUE TITLE
How to use acknowledged commands?

### ISSUE THREAD

**Issue by therealprof** [ntex-rs/ntex-mqtt#12]
Trying to use `publish_qos1` instead of `publish_qos0` doesn't seem to work as intended, if I `.await` the result the packet is never sent over the wire and the execution just hangs. If I don't `.await` (and ignore the violent warning from rustc that async functions must be polled to achieve something) and follow uo with a `publish_qos0` I can see that both packets are batched up and sent back-to-back in the same TCP packet to the broker.

I was trying to implement SUBSCRIBE support but that suffers from the same problem.

**Comment by fafhrd91** [comment]
I’ve never use it as client. I’ll check and add example

**Comment by therealprof** [comment]
Any news on this?

**Comment by fafhrd91** [comment]
new client api implement acks and subscribe/unsubscribe
