### ISSUE TITLE
How to define return type of `v3::MqttServer::new`

### ISSUE THREAD

**Issue by svanharmelen** [ntex-rs/ntex-mqtt#126]
I'm working on a project that is trying to use `ntex-mqtt` and so far it seems to work out pretty well. So first of all thanks for this amazing framework!!

Now my issue is with defining the function signature of a function that returns the result of `v3::MqttServer::new`. The function looks like this:

```rust
fn new_server_v3(
    <snip>
) -> v3::MqttServer<ClientSession, ?, ?, ?> {
    v3::MqttServer::new(|handshake: v3::Handshake| async {
       // do some prep stuff

        let session = ClientSession {
            <snip>
        };

        Ok::<_, ServerError>(handshake.ack(session, false))
    })
    .control(control_service_factory_v3())
    .publish(fn_factory_with_config(
        |session: v3::Session<ClientSession>| {
            Ready::Ok::<_, ServerError>(fn_service(move |req| publish_v3(session.clone(), req)))
        },
    ))
}
```

For readability and because this function takes some variables that we need later again to create the v5 server, we really prefer to create this function instead of defining it inline. Can you maybe tell me how to define the type of how I should be able to find that out by myself?

Thanks!!

**Comment by fafhrd91** [comment]
do you need something like [this](https://github.com/ntex-rs/ntex-mqtt/blob/master/examples/mqtt-ws-server.rs#L34)?

**Comment by svanharmelen** [comment]
That's pretty close, but still slightly different... In our case we in the end have something like this:

```rust
let server_v3 = server_v3(...);
let server_v6 = server_v5(...);

MqttServer::new().v3(server_v3).v5(server_v5)
```

So it's about the type the is expected by `MqttServer::new().v3(...)` and `MqttServer::new().v5(...)`. If I change my result type to the `impl` from the example (just for testing) it gives me this error:

```rust
expected struct `ntex_mqtt::v3::MqttServer<_, _, _, _>`
found opaque type `impl ServiceFactory<ntex::io::Io<[type error]>, [type error], Response = (), Error = [type error], InitError = ()>`
```

**Comment by fafhrd91** [comment]
it is not possible to write type with closures (at least i dont know)
other option would be to use service::boxed::BoxServiceFabric<>

**Comment by svanharmelen** [comment]
Well, I guess you are right about that (not possible to write a type with closures). At least I'm not able to find a way either 😊 

So any pointers (no pun intended 😉 ) to the other option? I searched the `ntex` org for `BoxServiceFabric` but got zero hits. Did find `BoxServiceFactory` and some in `boxed.rs`, but not much examples on how I would approach that..

**Comment by fafhrd91** [comment]
[BoxServiceFactory](https://docs.rs/ntex/0.5.31/ntex/service/boxed/struct.BoxServiceFactory.html), just define all params same as in ServiceFactory trait. you can create it with [factory](https://docs.rs/ntex/0.5.31/ntex/service/boxed/fn.factory.html) helper

**Comment by svanharmelen** [comment]
I'll have a closer look. Thanks for help so far!
