### ISSUE TITLE
example to have secure MQTT connection to port 8883

### ISSUE THREAD

**Issue by xudesheng** [ntex-rs/ntex-mqtt#13]
I'm trying to use this client and connect to Azure IoTHub via MQTT on port 8883 but I can't find an API to load CA root cert. (BaltimoreCyberTrustRoot.crt.pem)

I can use Python Paho lib to valid and have connected to Azure IoTHub via MQTT directly.

**Comment by fafhrd91** [comment]
`MqttConnector::openssl()` or `MqttConnector::rustls()`
