### ISSUE TITLE
mqtt-ws-server.rs for ws

### ISSUE THREAD

**Issue by tryor** [ntex-rs/ntex-mqtt#133]
Hello, in mqtt-ws-server.rs example, I want to remove openssl. How to modify it?

**Comment by botika** [comment]
Need change that https://github.com/ntex-rs/ntex-mqtt/blob/9e5dae84d6d6fe32592e11ccb3a0eb4a9a80c760/examples/mqtt-ws-server.rs#L80

**Comment by tryor** [comment]
thank you!
