### ISSUE TITLE
generic associated types are unstable

### ISSUE THREAD

**Issue by DineshSomalingam** [ntex-rs/ntex-mqtt#138]
I'm a NOOB to Rust, but when I try to compile the code under examples router_v5, getting the below error. Would appreciate any help/hints  in resolving this

error[E0658]: generic associated types are unstable
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/ntex-service-1.0.2/src/and_then.rs:41:5
   |
41 |     type Future<'f> = AndThenServiceResponse<'f, A, B, Req> where Self: 'f, Req: 'f;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

**Comment by fafhrd91** [comment]
you need newer version of rust, min supported version of rust is 1.65
