### ISSUE TITLE
KeepAlive is not working for PingRequest

### ISSUE THREAD

**Issue by f-agnes** [ntex-rs/ntex-mqtt#14]
I'm testing using basic example and having three issues with a client disconnect timeout:

1 - The client got disconnected before send ping request to the server; 
2 - If I change the server source code to configure timeout as 1.5 times the value of keepalive, client will continue to disconnecting because the ping request package doesn't refresh the keepalive timer as publish packet does;
3 - When client try to disable keepalive (keepalive = 0), the connection are closed immediataly.

The client only connect to server and subscribe to one topic. If client send publish messages periodicaly, the connection keep alive

**Comment by fafhrd91** [comment]
fixed in new client api, v0.3.5
