### ISSUE TITLE
How to connect using a username and password

### ISSUE THREAD

**Issue by qcjxberin** [ntex-rs/ntex-mqtt#141]
As a server, how to ensure that the client must verify the account and password when connecting

**Comment by fafhrd91** [comment]
you can verify Connect packet in handshake service. [example](https://github.com/ntex-rs/ntex-mqtt/blob/7902800de732b52d3fa9d0aa91f7b10e299c3553/examples/session.rs#L29)

**Comment by fafhrd91** [comment]
https://docs.rs/ntex-mqtt/0.10.4/ntex_mqtt/v3/struct.Handshake.html
