### ISSUE TITLE
not found in `crate::rt`

### ISSUE THREAD

**Issue by qcjxberin** [ntex-rs/ntex-mqtt#144]
Create a new project, then reference ntex-mqtt = "0.11.0-beta.3", and report an error when using cargo run
![image](https://github.com/ntex-rs/ntex-mqtt/assets/5792218/43f6f671-71ac-45c5-b2b5-5c4dd63185b0)

**Comment by qcjxberin** [comment]
![image](https://github.com/ntex-rs/ntex-mqtt/assets/5792218/7ab1e46e-fd30-436e-9d81-b229842f431b)

**Comment by fafhrd91** [comment]
add `ntex = { version = “0.7.0-beta.1, features = [“tokio”] }` to cargo.toml

**Comment by qcjxberin** [comment]
Tks
