### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by qcjxberin** [ntex-rs/ntex-mqtt#146]
![image](https://github.com/ntex-rs/ntex-mqtt/assets/5792218/2ddbe3c4-63fd-4aa1-8b96-aeccd599e300)
![image](https://github.com/ntex-rs/ntex-mqtt/assets/5792218/10aace0f-04b7-47c4-9398-5f032f2e8d8f)
![image](https://github.com/ntex-rs/ntex-mqtt/assets/5792218/9970fb28-5d8d-4167-a221-6ab1b7152a4d)

**Comment by fafhrd91** [comment]
https://github.com/rust-lang/rust/issues/107513

**Comment by fafhrd91** [comment]
fixed with rust-1.72
