### ISSUE TITLE
Is there any reason removing the example `mqtt-ws-server.rs`?

### ISSUE THREAD

**Issue by evshary** [ntex-rs/ntex-mqtt#176]
I found that `mqtt-ws-server.rs` is removed after the PR.
https://github.com/ntex-rs/ntex-mqtt/pull/167
Does that mean `ntex-mqtt` doesn't support this anymore?

**Comment by 24icewolf42** [comment]
It seems that the example was removed because of refactoring `ws` part of ntex. Would it be possible to add this example here again? Just because there is also no other `ws` example currently available showcasing the upgrade to another protocol.

**Comment by fafhrd91** [comment]
added new version
