### ISSUE TITLE
how to let ntex-rt and actix-rt work together?

### ISSUE THREAD

**Issue by xudesheng** [ntex-rs/ntex-mqtt#30]
I'm working on a use case to translate MQTT message to a WebSocket based message without MQTT Broker. So, my tool has to play two roles: MQTT broker and Websocket client.
My WebSocket client is based on Actix Actor and therefore it needs actix-rt. Glad to see that Actix-MQTT becomes ntex-mqtt now, my questions:
#1) Is it possible to let ntex-rt and actix-rt work together?
#2) if not, is there any way to let both of them running in tokio runtime?

Always thanks to the great work done by. @fafhrd91

**Comment by fafhrd91** [comment]
at the moment you can not mix runtimes. but i would suggest against actix actors for your issue. websockets connector returns Framed object, then it is possible to wrap it and provide AsyncRead/Write. i can provide example how to wrap framed object. i will try to create complete example a bit later.

**Comment by xudesheng** [comment]
> at the moment you can not mix runtimes. but i would suggest against actix actors for your issue. websockets connector returns Framed object, then it is possible to wrap it and provide AsyncRead/Write. i can provide example how to wrap framed object. i will try to create complete example a bit later.

@fafhrd91 thank you for your reply and sorry for late response.
very appreciate if you give me some example. 

My goal is to provide 30K message throughput on a Azure D4s VM.

**Comment by xudesheng** [comment]
Hi, @fafhrd91 , could you kindly please consider this issue: [https://github.com/ntex-rs/ntex/issues/27](https://github.com/ntex-rs/ntex/issues/27)  too? this is the issue that blocks me to move from actix_rt to ntex_rt for WebSocket.
