### ISSUE TITLE
Server responds with "Maximum Packet Size" = 0 by default

### ISSUE THREAD

**Issue by ctron** [ntex-rs/ntex-mqtt#34]
By default, the MQTT v5 server responds with a maximum packet size of zero:

![image](https://user-images.githubusercontent.com/202474/93085654-2be24d80-f696-11ea-96c9-15db36313cb8.png)

However, according to the spec, this is not allowed:

> It is a Protocol Error to include the Maximum Packet Size more than once, or for the value to be set to zero.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901050

I guess this is due to the fact, that the `MqttServer` is initialized with `0`:

https://github.com/ntex-rs/ntex-mqtt/blob/828e696939d29068f216bf1a4523c6dbf698c545/src/v5/server.rs#L61

To my understanding, in the case of "unlimited", it should simply be omitted:

>  If the Maximum Packet Size is not present, no limit on the packet size is imposed beyond the limitations in the protocol as a result of the remaining length encoding and the protocol header sizes.

**Comment by ctron** [comment]
During the handshake, the function simply overwrites the result, coming from the connect handler, with the value from the server:

https://github.com/ntex-rs/ntex-mqtt/blob/828e696939d29068f216bf1a4523c6dbf698c545/src/v5/server.rs#L421

The value in the connect ack is actually an `Option`.

So me it would make sense to honor the values from the connect ack struct, as long as they are below the server maximum. If the value from connect ack is `None`, and the server maximum is zero, then `None` should be set, which would drop the value from the encoded package.

Aside from that, I think the handshake should also honor the other values and not overwrite them:

https://github.com/ntex-rs/ntex-mqtt/blob/828e696939d29068f216bf1a4523c6dbf698c545/src/v5/server.rs#L422-L423

**Comment by ctron** [comment]
If you want, I can try coming up with a fix for this.

**Comment by fafhrd91** [comment]
good catch. max size should be omitted if it set to 0

**Comment by fafhrd91** [comment]
I agree regarding topic_alias_max and max_qos

**Comment by fafhrd91** [comment]
@ctron would you like to submit pr for this issue?

**Comment by fafhrd91** [comment]
fixed in master

**Comment by ctron** [comment]
> fixed in master

Thanks! I am sorry I couldn't time for this so far.

**Comment by fafhrd91** [comment]
no problem
