### ISSUE TITLE
bridge support

### ISSUE THREAD

**Issue by GopherJ** [ntex-rs/ntex-mqtt#39]
Hi, would you be interested in adding bridge support?

**Comment by fafhrd91** [comment]
what kind of bridge?

**Comment by GopherJ** [comment]
@fafhrd91 Hi, seems like mosquitto's bridge, I think it's also an important feature for broker because it connects every component of a big application.

http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

**Comment by fafhrd91** [comment]
i see. i think, you should be able to create bridge on top of ntex-mqtt. ntex-mqtt is a franework, it does not provide any concrete app/utility

**Comment by GopherJ** [comment]
@fafhrd91 ntex-mqtt is a mqtt broker & client to my understandings, I want this because if it exists I then don't need to install another broker like `mosquitto` or `emqx`.

**Comment by fafhrd91** [comment]
ntex-mqtt is a general purpose mqtt server and client framework

**Comment by fafhrd91** [comment]
i am happy to modify ntex-mqtt if you will need anything for ntex-mqtt-broker
