### ISSUE TITLE
Allow getting access to the underlying socket

### ISSUE THREAD

**Issue by ctron** [ntex-rs/ntex-mqtt#43]
Maybe this is already possible, and I just couldn't find a way.

We would need access to the underlying socket of the connection, at least for handling the "connect" request.

Our use case is that, when handling the "connect" packet, we need the have access to the X.509 client certificates (if any) for validation. Both openssl and rustls provide calls to extract this information from the socket. However, I couldn't find a way to get access to the socket.

I do understand that, depending on the implementation type, the socket could be of a different type. However, others seem to solve this by using a `dyn &Any` argument, which you can then "downcast", to check if for the concrete type. I guess other ways should also be possible.

If it helps, I would try to create a PR to fix this issue. However, I didn't have any plan yet on how to achieve this.

**Comment by ctron** [comment]
Ok, after a bit of digging, I found a solution:

~~~rust
pub async fn connect_v3<Io: Any + 'static>(
    mut connect: v3::Connect<Io>,
    app: App,
) -> Result<v3::ConnectAck<Io, Session>, ServerError> {
    let io: &dyn Any = connect.io().get_ref();
    if let Some(tls) =
        io.downcast_ref::<ntex::server::rustls::TlsStream<ntex::rt::net::TcpStream>>()
    {
        let certs = tls.get_ref().1.get_peer_certificates();
        log::info!("Certs: {:?}", certs);
    }

    // handle connect here
}
~~~

Of course this works only when using "rustls". However, you can make it work with openssl, choosing a type of `ntex::server::openssl::SslStream<ntex::rt::net::TcpStream>`.

So I guess this could be resolved with some documentation, or an example. Or maybe this issue is documentation enough :)

Let me know what you think and I am trying to help.

**Comment by fafhrd91** [comment]
this is documentation issue. just replace `Io` with SslStream<TcpStream>

**Comment by fafhrd91** [comment]
openssl example is almost the same as rustls, just use https://docs.rs/ntex/0.2.0-b.11/ntex/server/openssl/struct.Acceptor.html instead of rustls

**Comment by fafhrd91** [comment]
I added openssl example https://github.com/ntex-rs/ntex-mqtt/blob/master/examples/openssl.rs
