### ISSUE TITLE
How to use Router?

### ISSUE THREAD

**Issue by qm3ster** [ntex-rs/ntex-mqtt#45]
When using `v5::Router` as the `publish` service, how can I access the path wildcard matches in the handler?

**Comment by fafhrd91** [comment]
what is your router code looks like?

in general, you can access matches via https://docs.rs/ntex-mqtt/0.6.4/ntex_mqtt/v5/struct.Publish.html#method.topic

and Path::get()  https://docs.rs/ntex-router/0.4.2/ntex_router/struct.Path.html

**Comment by qm3ster** [comment]
That is amazing! I just assoomed that `.topic()` would just return `&str` or something anemic like that.
### 1. However, I don't think I understand how router nesting should be carried out.
```rs
.publish(v3::Router::new(default_service.clone()).resource(
    "{one}/{tail}*",
    v3::Router::new(default_service).resource(
        "{two}/{tail2}*",
        fn_factory_with_config(|ses: v3::Session<MySession>| {
            println!("{:?} {:?}", ses.sink(), ses.state());
            ok::<_, MyServerError>(fn_service(
                async move |publish: v3::Publish| {
                    println!("wow, a special publish!\n{:?}", publish);
                    for (k, v) in publish.topic().iter() {
                        println!("{}: {}", k, v);
                    }
                    Ok(())
                },
            ))
        }),
    ),
)))
```
for `"hello/1/2/3"` produces
```
one: hello
tail: 1/2/3
two: 2
tail2: 3
```
Changing `"{one}/{tail}*"` to `"{one}/*"` does the same (but doesn't name `tail` at all). How would I get a named segment that matches `1` in this case?

### 2. Is there a way to create a middleware that wraps a `Router` or a any other... `ServiceFactory`(?) that could filter or mutate a request before it's passed to the inner type? Maybe there's an example in a non-mqtt-specific repo?

### 3. Has anyone attempted at least a naive implementation of a somewhat compliant mqtt broker using this networking facade? Something that actually stores subscriptions and routes messages based on that? Notably, this would probably involve getting an `MqttSink` from the `Handshake` and registering it in some BrokerRouter "agent"(?) which should also be addressable from `MySession` to be configured in a control message service?

**Comment by fafhrd91** [comment]
router couldn't be used for broker, nesting is not supported as well. broker must implement its own routing.
