### ISSUE TITLE
MQTT 5 support

### ISSUE THREAD

**Issue by therealprof** [ntex-rs/ntex-mqtt#5]
I just noticed that there's a v5 branch. Is this going to be integrated into master as the official MQTT 5 support or is this just a random side gig.

I'd be very interested in contributing and would like to know the way forward here.

**Comment by fafhrd91** [comment]
We are planing to merge it to master soon.

**Comment by therealprof** [comment]
Another question: What is the plan concerning 3.1.1 support:

Will 3.1.1 be dropped? Or will the version be selected via feature flag? Or will there be concurrent support for both versions (and if so will there be some magic to automatically handle the version of outgoing/incoming packets or will it be up to the user of the codec to produce and handle the right MQTT version?)?

**Comment by fafhrd91** [comment]
we will support 3.1.1 for the foreseeable future. server framework will automatically switch codecs depends on protocol version

**Comment by therealprof** [comment]
Nice, wouldn't it make sense then to treat the messages which are different in 3.1.1 vs 5.0 separately so that the codec is able to decode both versions? The v5 branch seems to completely remove 3.1.1 support by rewritting the structures to the v5 version and hardcoding the protocol.

**Comment by fafhrd91** [comment]
we will have both codecs in master. v5 is just wip

**Comment by fafhrd91** [comment]
in master
