### ISSUE TITLE
How to respond to Qos1 subscription in v5

### ISSUE THREAD

**Issue by StanLi-ops** [ntex-rs/ntex-mqtt#61]
Hello, I am having trouble responding to the subscription.
I imitated the implementation of drogue-cloud/mqtt-integration and wanted to make a Mqtt Broker. [https://github.com/drogue-iot/drogue-cloud/blob/main/mqtt-integration/src](url)
Everything looked normal at first.
drogue-cloud/mqtt-integration only implements subscription (Qos 0).
I hope to support Qos 1.
There was a problem when I replaced **_send_at_most_once()_** with **_send_at_least_once()_**：
-  The client terminal automatically closes after receiving the subscription information once.

Related information I know so far:
- **_send_at_least_once()_** returns **_PublishQos1Error::Disconnected_**
- Received v5::ControlMessage::ProtocolError in Control

The error is as follows：
```
[2021-09-06T11:01:27Z INFO  session] Hello
[2021-09-06T11:01:27Z INFO  ntex::server::builder] Starting 1 workers
[2021-09-06T11:01:27Z INFO  ntex::server::builder] Starting "mqtt" service on 127.0.0.1:1883
[2021-09-06T11:01:34Z INFO  session] new connection: Connect { clean_start: true, keep_alive: 60, session_expiry_interval_secs: None, auth_method: None, auth_data: None, request_problem_info: true, request_response_info: false, receive_max: None, topic_alias_max: 0, user_properties: [], max_packet_size: None, last_will: Some(LastWill { qos: AtLeastOnce, retain: false, topic: "aaaaaaaa", message: b"aaaaaaaaaaaaaaaaaaaaaa", will_delay_interval_sec: Some(5), correlation_data: None, message_expiry_interval: Some(5), content_type: Some("aaaaaaaa"), user_properties: [], is_utf8_payload: Some(true), response_topic: None }), client_id: "mqttx_6dfcaa94", username: Some("admin"), password: Some(b"1234567") }
[2021-09-06T11:01:34Z ERROR session] ProtocolError { err: Decode(MalformedPacket), pkt: Disconnect { reason_code: ImplementationSpecificError, session_expiry_interval_secs: None, server_reference: None, reason_string: None, user_properties: [] } }
[2021-09-06T11:01:34Z ERROR session] Disconnected
```

This is a simple example of modifying examples/session.rs, which is the same as the error I made in practice.(Other codes are the same as examples/session.rs)：

```rust
async fn control_v5<E>(
    session: v5::Session<MySession>,
    control: v5::ControlMessage<E>,
) -> Result<v5::ControlResult, MyServerError> {
    match control {
        v5::ControlMessage::Auth(a) => {
            // we don't do extended authentication (yet?)
            Ok(a.ack(Auth::default()))
        }
        v5::ControlMessage::Error(e) => Ok(e.ack(DisconnectReasonCode::UnspecifiedError)),
        v5::ControlMessage::ProtocolError(pe) => {
            error!("{:?}", pe);
            Ok(pe.ack())
        }
        v5::ControlMessage::Ping(p) => Ok(p.ack()),
        v5::ControlMessage::Disconnect(d) => Ok(d.ack()),
        v5::ControlMessage::Subscribe(mut s) => {
            s.iter_mut().for_each(|mut s| {
                let sink = session.sink().clone();
                let topic = s.topic().clone();
                ntex::rt::spawn(async move {
                    match sink.publish(topic, Bytes::from("A")).send_at_least_once().await {
                        Ok(w) => {
                            error!("{:?}", w)
                        }
                        Err(e) => {
                            error!("{:?}", e)
                        }
                    };
                });
                s.subscribe(v5::QoS::AtLeastOnce);
            });

            Ok(s.ack())
        }
        v5::ControlMessage::Unsubscribe(u) => Ok(u.ack()),
        v5::ControlMessage::Closed(c) => Ok(c.ack()),
    }
}
```
How should I respond to the subscription correctly (Qos 1)？

**Comment by StanLi-ops** [comment]
I found that **_DecodeError::MalformedPacket_** is returned by the **_ensure!_** in **_decode_variable_length_cursor( )_**.
The reason is because **_src.has_remaining()_** returns false.
I read the relevant notes about **_has_remaining()_**, but still don't understand what I did in **_send_at_least_once()_** that caused **_has_remaining()_** to return false.
```rust
#[allow(clippy::cast_lossless)] // safe: allow cast through `as` because it is type-safe
pub(crate) fn decode_variable_length_cursor<B: Buf>(src: &mut B) -> Result<u32, DecodeError> {
    let mut shift: u32 = 0;
    let mut len: u32 = 0;
    loop {
        ensure!(src.has_remaining(), DecodeError::MalformedPacket);  // DecodeError::MalformedPacket is returned here
        let val = src.get_u8();
        len += ((val & 0b0111_1111u8) as u32) << shift;
        if val & 0b1000_0000 == 0 {
            return Ok(len);
        } else {
            ensure!(shift < 21, DecodeError::InvalidLength);
            shift += 7;
        }
    }
}
```
What caused the problem and how can I avoid it?

**Comment by fafhrd91** [comment]
do you use ntex-mqtt 0.6 or 0.7-b?

**Comment by StanLi-ops** [comment]
> 你使用 ntex-mqtt 0.6 还是 0.7-b？

The original version used was "0.6.9". Now, when I update the version to "0.7.0-b.8", the above problem still exists.
This is the version information related to ntex：
```toml
ntex-mqtt = "0.7.0-b.8"
ntex-rt = "0.3.1"
ntex = { version = "0.4.0-b.6", features = ["rustls", "openssl"] }
ntex-bytes = "0.1.4"
ntex-router = "0.5.1"
```

**Comment by fafhrd91** [comment]
I cannot reproduce your problem. Could you provide reproducible example.

I also added "subs" and "subs_client" examples.

**Comment by StanLi-ops** [comment]
It seems to be a client-side problem.

I used the sub_client you provided to access sub and the Broker program I wrote, and everything worked fine.
But when I used the free MQTT client "MQTT X" provided by EMQ to access the sub provided by you, the same error as above occurred.

In addition, I used an MQTT client written by GO to access sub_client and everything was normal.

It seems that I need to avoid using "MQTT X" for testing.
Thank you very much for your help and the subscription example you provided.

If you are interested, you can download this client to reproduce the error.
"MQTT X" client download address: [https://github.com/emqx/MQTTX/releases](url)
