### ISSUE TITLE
MQTT v5 sends out subscription ID 1 as 0 (protocol error)

### ISSUE THREAD

**Issue by ctron** [ntex-rs/ntex-mqtt#73]
Sending out a subscription ID of 1 gets translated into "0":

![image](https://user-images.githubusercontent.com/202474/140286754-f431a88f-bc84-49b2-9023-e95ed8786955.png)

However, sending "0" is a protocol error:

§ 3.3.2.3.8
>  It is a Protocol Error if the Subscription Identifier has a value of 0.

**Comment by ctron** [comment]
Taking a look a the bytes, I think the ID is encoded in the wrong way. It should be a "Variable Byte Integer", but even for "1" it becomes `\x00\x00\x00\x01` … so the "first" byte is decoded by the client as 0 (zero), which is a identified as a protocol error.

**Comment by ctron** [comment]
The PR fixes the issue for me. I noticed that the same problem occurs encoding the Subscription packet. The PR fixes both.

**Comment by fafhrd91** [comment]
v0.7.5 is released
