### ISSUE TITLE
SubscribeAckReason enum has a typo

### ISSUE THREAD

**Issue by petergmiller** [ntex-rs/ntex-mqtt#93]
Definitely not a major issue, but I observed that the SubscribeAckReason enum value for SharedSubsriptionNotSupported has Subscription misspelled: https://github.com/ntex-rs/ntex-mqtt/blob/8fdf3f112c6cbfc75ee20a63b377e907f79f9e74/src/v5/codec/packet/subscribe.rs#L81

I'm happy to correct the issue myself, but unsure how you want to approach what would technically be a breaking change for consumers of the library?  Obviously this enum value being misspelled is not a functionality issue, but I figured I would open the issue in case cleaning it up is of interest to you.

**Comment by fafhrd91** [comment]
fixed with #94
