### ISSUE TITLE
Subs.rs example uses .subscribe() which is unlisted in docs as opposed to .confirm()

### ISSUE THREAD

**Issue by petergmiller** [ntex-rs/ntex-mqtt#97]
The subs.rs example here https://github.com/petergmiller/ntex-mqtt/blob/master/examples/subs.rs uses .subscribe to indicate successful subscription, as opposed to using confirm.  While either appear to be acceptable (as subscribe just calls confirm), it seems that confirm would be preferable as subscribe is hidden in docs (https://github.com/ntex-rs/ntex-mqtt/blob/58141768f7532d1193bf7b725d311a2097dfb1b3/src/v5/control.rs#L287).

**Comment by fafhrd91** [comment]
i dont really remember reason

**Comment by fafhrd91** [comment]
i will make new release later today
